javascript_compressor: closure
javascripts:
  common:
    - public/javascripts/vendor/modernizr.js
    - public/javascripts/vendor/jquery.js
    - public/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/screen.css
  print:
    - public/stylesheets/print.css
  ie:
    - public/stylesheets/ie.css

